module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.46,True,2023-06-01T07:00:22,,
cowidev.vax.batch.australia,,,2023-06-01T07:00:07,,
cowidev.vax.batch.austria_old,,,2023-06-01T07:00:07,,
cowidev.vax.batch.belgium,15.32,True,2023-06-01T07:00:22,,
cowidev.vax.batch.bolivia,4.08,True,2023-06-01T07:00:11,,
cowidev.vax.batch.canada,5.35,False,2023-06-01T07:02:02,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 96, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']. Location(s) affected: {'Canada'}
",1 chunks of lengths 36 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']. Location(s) affected: {'Canada'}
cowidev.vax.batch.chile,1.41,True,2023-06-01T07:00:08,,
cowidev.vax.batch.czechia,29.92,True,2023-06-01T07:00:37,,
cowidev.vax.batch.denmark,,,2023-06-01T07:00:07,,
cowidev.vax.batch.ecdc,95.17,True,2023-06-01T07:01:42,,
cowidev.vax.batch.ecuador,,,2023-06-01T07:00:07,,
cowidev.vax.batch.estonia,7.58,True,2023-06-01T07:00:14,,
cowidev.vax.batch.france,6.98,True,2023-06-01T07:00:14,,
cowidev.vax.batch.germany,0.19,True,2023-06-01T07:00:07,,
cowidev.vax.batch.greece,22.47,True,2023-06-01T07:00:29,,
cowidev.vax.batch.hong_kong,16.93,True,2023-06-01T07:00:24,,
cowidev.vax.batch.indonesia,,,2023-06-01T07:00:07,,
cowidev.vax.batch.ireland,0.33,False,2023-06-01T07:02:03,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 135, in main
    Ireland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 130, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 27, in read
    return pd.merge(data_primary, data_booster, how=""outer"", on=""date"", validate=""one_to_one"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 106, in merge
    op = _MergeOperation(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 709, in __init__
    self._validate(validate)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 1429, in _validate
    raise MergeError(
pandas.errors.MergeError: Merge keys are not unique in right dataset; not a one-to-one merge
",Merge keys are not unique in right dataset; not a one-to-one merge
cowidev.vax.batch.israel,6.6,True,2023-06-01T07:00:13,,
cowidev.vax.batch.italy,12.56,True,2023-06-01T07:00:19,,
cowidev.vax.batch.japan,9.8,False,2023-06-01T07:02:12,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 375, in main
    Japan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 359, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 71, in read
    df_latest = self.read_latest().pipe(self.pipe_read_latest)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 100, in read_latest
    self._read_latest_booster(),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 211, in _read_latest_booster
    df = self._read_xlsx(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 233, in _read_xlsx
    raise ValueError(f""Unknown sheets: {sheets_unknown}"")
ValueError: Unknown sheets: {'5.8以降接種_一般接種（６回目）', '５回目_一般接種回数', '６回目_一般接種回数', '5.8以降接種_一般接種（５回目）', '5.8以降接種_総接種回数', '5.8以降接種_一般接種（４回目）', '６回目_総接種回数', '5.8以降接種_一般接種（３回目）', '５回目_総接種回数'}
","Unknown sheets: {'5.8以降接種_一般接種（６回目）', '５回目_一般接種回数', '６回目_一般接種回数', '5.8以降接種_一般接種（５回目）', '5.8以降接種_総接種回数', '5.8以降接種_一般接種（４回目）', '６回目_総接種回数', '5.8以降接種_一般接種（３回目）', '５回目_総接種回数'}"
cowidev.vax.batch.jersey,5.61,True,2023-06-01T07:00:12,,
cowidev.vax.batch.latvia,59.12,True,2023-06-01T07:01:06,,
cowidev.vax.batch.lithuania,4.96,True,2023-06-01T07:00:12,,
cowidev.vax.batch.luxembourg,0.74,False,2023-06-01T07:02:13,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 88, in main
    Luxembourg().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 83, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 78, in pipeline
    .pipe(self.pipe_correct_time_series)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 47, in pipe_correct_time_series
    df = add_latest_who_values(df, ""Luxembourg"", [""people_fully_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.malaysia,1.05,True,2023-06-01T07:00:08,,
cowidev.vax.batch.malta,1.02,True,2023-06-01T07:00:08,,
cowidev.vax.batch.netherlands,,,2023-06-01T07:00:07,,
cowidev.vax.batch.new_zealand,12.89,True,2023-06-01T07:00:20,,
cowidev.vax.batch.norway,1.65,True,2023-06-01T07:00:08,,
cowidev.vax.batch.peru,5.24,True,2023-06-01T07:00:12,,
cowidev.vax.batch.portugal,,,2023-06-01T07:00:07,,
cowidev.vax.batch.romania,2.34,False,2023-06-01T07:02:16,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 159, in main
    Romania().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 144, in export
    df = df_base.copy().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 126, in pipeline
    .pipe(add_latest_who_values, ""Romania"", [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.saudi_arabia,0.55,False,2023-06-01T07:02:16,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 82, in main
    SaudiArabia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 59, in pipeline
    return df.pipe(self.make_monotonic).pipe(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.singapore,5.27,True,2023-06-01T07:00:12,,
cowidev.vax.batch.slovakia,48.02,True,2023-06-01T07:00:55,,
cowidev.vax.batch.slovenia,2.19,True,2023-06-01T07:00:09,,
cowidev.vax.batch.south_korea,9.14,False,2023-06-01T07:02:25,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 209, in main
    SouthKorea().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 191, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 109, in pipeline_base
    .pipe(self.pipe_check_metrics)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 92, in pipe_check_metrics
    raise ValueError(f""Metric {dose} for 'all' is not equal to the sum over all vaccines (2% tolerance)."")
ValueError: Metric dose_1 for 'all' is not equal to the sum over all vaccines (2% tolerance).
",Metric dose_1 for 'all' is not equal to the sum over all vaccines (2% tolerance).
cowidev.vax.batch.spc,30.38,True,2023-06-01T07:00:37,,
cowidev.vax.batch.sweden,18.18,True,2023-06-01T07:00:26,,
cowidev.vax.batch.switzerland,59.95,True,2023-06-01T07:01:08,,
cowidev.vax.batch.trinidad_and_tobago,3.83,True,2023-06-01T07:00:12,,
cowidev.vax.batch.ukraine,,,2023-06-01T07:00:08,,
cowidev.vax.batch.united_kingdom,17.48,True,2023-06-01T07:00:26,,
cowidev.vax.batch.united_states,20.5,True,2023-06-01T07:00:29,,
cowidev.vax.batch.uruguay,6.99,True,2023-06-01T07:00:16,,
cowidev.vax.batch.zimbabwe,1.73,True,2023-06-01T07:00:13,,
cowidev.vax.incremental.africacdc,,,2023-06-01T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-06-01T07:00:11,,
cowidev.vax.incremental.aruba,1.47,True,2023-06-01T07:00:12,,
cowidev.vax.incremental.austria,,,2023-06-01T07:00:12,,
cowidev.vax.incremental.azerbaijan,,,2023-06-01T07:00:12,,
cowidev.vax.incremental.bahrain,,,2023-06-01T07:00:12,,
cowidev.vax.incremental.bangladesh,53.08,True,2023-06-01T07:01:05,,
cowidev.vax.incremental.barbados,,,2023-06-01T07:00:12,,
cowidev.vax.incremental.brazil,0.99,True,2023-06-01T07:00:13,,
cowidev.vax.incremental.bulgaria,0.68,False,2023-06-01T07:02:26,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 68, in main
    Bulgaria().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 63, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 59, in pipeline
    .pipe(add_latest_who_values, self.location, [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.incremental.china,18.58,True,2023-06-01T07:00:31,,
cowidev.vax.incremental.costa_rica,,,2023-06-01T07:00:12,,
cowidev.vax.incremental.croatia,1.14,True,2023-06-01T07:00:13,,
cowidev.vax.incremental.cuba,17.17,True,2023-06-01T07:00:29,,
cowidev.vax.incremental.curacao,,,2023-06-01T07:00:13,,
cowidev.vax.incremental.cyprus,3.67,True,2023-06-01T07:00:16,,
cowidev.vax.incremental.dominican_republic,14.16,False,2023-06-01T07:02:40,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 112, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 91, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 81, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,8.85,True,2023-06-01T07:00:22,,
cowidev.vax.incremental.faeroe_islands,1.07,True,2023-06-01T07:00:14,,
cowidev.vax.incremental.fiji,0.0,True,2023-06-01T07:00:14,,
cowidev.vax.incremental.finland,0.72,True,2023-06-01T07:00:14,,
cowidev.vax.incremental.gabon,,,2023-06-01T07:00:14,,
cowidev.vax.incremental.georgia,5.5,True,2023-06-01T07:00:20,,
cowidev.vax.incremental.greenland,,,2023-06-01T07:00:14,,
cowidev.vax.incremental.guatemala,,,2023-06-01T07:00:14,,
cowidev.vax.incremental.guernsey,,,2023-06-01T07:00:14,,
cowidev.vax.incremental.hungary,83.03,True,2023-06-01T07:01:37,,
cowidev.vax.incremental.iceland,2.77,True,2023-06-01T07:00:17,,
cowidev.vax.incremental.india,1.92,True,2023-06-01T07:00:18,,
cowidev.vax.incremental.iran,,,2023-06-01T07:00:16,,
cowidev.vax.incremental.isle_of_man,2.67,True,2023-06-01T07:00:19,,
cowidev.vax.incremental.jamaica,10.81,True,2023-06-01T07:00:28,,
cowidev.vax.incremental.kazakhstan,8.85,True,2023-06-01T07:00:26,,
cowidev.vax.incremental.kosovo,,,2023-06-01T07:00:18,,
cowidev.vax.incremental.kyrgyzstan,3.71,True,2023-06-01T07:00:22,,
cowidev.vax.incremental.laos,2.48,True,2023-06-01T07:02:43,,
cowidev.vax.incremental.macao,7.85,False,2023-06-01T07:02:50,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 90, in main
    Macao().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 75, in export
    data = self.read()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 23, in read
    iframe_url = self._get_iframe_url(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 31, in _get_iframe_url
    elem = driver.find_element_by_id(""ICovid19Monitor"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=113.0.5672.126)

","Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=113.0.5672.126)
"
cowidev.vax.incremental.moldova,,,2023-06-01T07:00:20,,
cowidev.vax.incremental.monaco,90.12,True,2023-06-01T07:01:50,,
cowidev.vax.incremental.mongolia,1.2,True,2023-06-01T07:00:21,,
cowidev.vax.incremental.montenegro,1.14,True,2023-06-01T07:00:21,,
cowidev.vax.incremental.morocco,,,2023-06-01T07:00:20,,
cowidev.vax.incremental.myanmar,,,2023-06-01T07:00:20,,
cowidev.vax.incremental.nepal,,,2023-06-01T07:00:20,,
cowidev.vax.incremental.north_macedonia,,,2023-06-01T07:00:20,,
cowidev.vax.incremental.northern_cyprus,6.42,True,2023-06-01T07:00:27,,
cowidev.vax.incremental.paho,85.2,False,2023-06-01T07:04:16,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 167, in pipeline
    df.pipe(self.pipe_check_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 122, in pipe_check_columns
    raise ValueError(f""Missing column fields: {columns_missing}. Present columns are: {df.columns}"")
ValueError: Missing column fields: {'Country/ Territory', 'Country code', '2nd additional dose', 'First dose', 'Second dose', '1st additional dose', 'Single dose', 'Total doses'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')
","Missing column fields: {'Country/ Territory', 'Country code', '2nd additional dose', 'First dose', 'Second dose', '1st additional dose', 'Single dose', 'Total doses'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')"
cowidev.vax.incremental.pakistan,,,2023-06-01T07:00:21,,
cowidev.vax.incremental.philippines,,,2023-06-01T07:00:21,,
cowidev.vax.incremental.poland,1.91,True,2023-06-01T07:00:23,,
cowidev.vax.incremental.qatar,,,2023-06-01T07:00:22,,
cowidev.vax.incremental.russia,27.84,True,2023-06-01T07:00:49,,
cowidev.vax.incremental.saint_lucia,,,2023-06-01T07:00:22,,
cowidev.vax.incremental.serbia,9.17,True,2023-06-01T07:00:31,,
cowidev.vax.incremental.south_africa,,,2023-06-01T07:00:22,,
cowidev.vax.incremental.spain,9.19,True,2023-06-01T07:00:31,,
cowidev.vax.incremental.sri_lanka,,,2023-06-01T07:00:22,,
cowidev.vax.incremental.suriname,16.11,True,2023-06-01T07:00:38,,
cowidev.vax.incremental.taiwan,5.22,False,2023-06-01T07:04:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 184, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 170, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 38, in read
    data = self.parse_data(df, soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 122, in parse_data
    ""date"": self._parse_date(soup),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 156, in _parse_date
    date_str = re.search(regex, date_raw).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
",'NoneType' object has no attribute 'group'
cowidev.vax.incremental.thailand,5.94,True,2023-06-01T07:00:30,,
cowidev.vax.incremental.turkey,,,2023-06-01T07:00:26,,
cowidev.vax.incremental.united_arab_emirates,,,2023-06-01T07:00:26,,
cowidev.vax.incremental.vietnam,,,2023-06-01T07:00:26,,
cowidev.vax.incremental.who,0.47,False,2023-06-01T07:04:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/who.py"", line 180, in main
    WHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/who.py"", line 175, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/who.py"", line 164, in pipeline
    df.pipe(self.pipe_checks)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/who.py"", line 42, in pipe_checks
    check_known_columns(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 166, in check_known_columns
    raise Exception(f""Unknown column(s) found: {unknown_cols}"")
Exception: Unknown column(s) found: {'PERSONS_LAST_DOSE', 'PERSONS_LAST_DOSE_PER100'}
","Unknown column(s) found: {'PERSONS_LAST_DOSE', 'PERSONS_LAST_DOSE_PER100'}"
cowidev.vax.incremental.zambia,0.7,False,2023-06-01T07:04:22,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 74, in main
    Zambia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 69, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 64, in pipeline
    .pipe(add_latest_who_values, ""Zambia"", [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
