module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.29,True,2023-06-02T07:00:22,,
cowidev.vax.batch.australia,,,2023-06-02T07:00:07,,
cowidev.vax.batch.austria_old,,,2023-06-02T07:00:07,,
cowidev.vax.batch.belgium,8.96,True,2023-06-02T07:00:16,,
cowidev.vax.batch.bolivia,3.56,True,2023-06-02T07:00:10,,
cowidev.vax.batch.canada,4.99,False,2023-06-02T07:01:56,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 96, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']. Location(s) affected: {'Canada'}
",1 chunks of lengths 36 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']. Location(s) affected: {'Canada'}
cowidev.vax.batch.chile,1.39,True,2023-06-02T07:00:08,,
cowidev.vax.batch.czechia,27.74,True,2023-06-02T07:00:34,,
cowidev.vax.batch.denmark,,,2023-06-02T07:00:07,,
cowidev.vax.batch.ecdc,84.78,True,2023-06-02T07:01:31,,
cowidev.vax.batch.ecuador,,,2023-06-02T07:00:07,,
cowidev.vax.batch.estonia,0.68,True,2023-06-02T07:00:07,,
cowidev.vax.batch.france,8.33,True,2023-06-02T07:00:15,,
cowidev.vax.batch.germany,0.24,True,2023-06-02T07:00:07,,
cowidev.vax.batch.greece,17.59,True,2023-06-02T07:00:24,,
cowidev.vax.batch.hong_kong,18.53,True,2023-06-02T07:00:25,,
cowidev.vax.batch.indonesia,,,2023-06-02T07:00:07,,
cowidev.vax.batch.ireland,0.47,False,2023-06-02T07:01:56,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 135, in main
    Ireland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 130, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/ireland.py"", line 27, in read
    return pd.merge(data_primary, data_booster, how=""outer"", on=""date"", validate=""one_to_one"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 106, in merge
    op = _MergeOperation(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 709, in __init__
    self._validate(validate)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py"", line 1429, in _validate
    raise MergeError(
pandas.errors.MergeError: Merge keys are not unique in right dataset; not a one-to-one merge
",Merge keys are not unique in right dataset; not a one-to-one merge
cowidev.vax.batch.israel,9.66,True,2023-06-02T07:00:16,,
cowidev.vax.batch.italy,10.54,True,2023-06-02T07:00:17,,
cowidev.vax.batch.japan,9.13,False,2023-06-02T07:02:05,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 375, in main
    Japan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 359, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 71, in read
    df_latest = self.read_latest().pipe(self.pipe_read_latest)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 100, in read_latest
    self._read_latest_booster(),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 211, in _read_latest_booster
    df = self._read_xlsx(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 233, in _read_xlsx
    raise ValueError(f""Unknown sheets: {sheets_unknown}"")
ValueError: Unknown sheets: {'５回目_一般接種回数', '5.8以降接種_一般接種（６回目）', '６回目_一般接種回数', '5.8以降接種_一般接種（３回目）', '5.8以降接種_一般接種（５回目）', '5.8以降接種_一般接種（４回目）', '５回目_総接種回数', '６回目_総接種回数', '5.8以降接種_総接種回数'}
","Unknown sheets: {'５回目_一般接種回数', '5.8以降接種_一般接種（６回目）', '６回目_一般接種回数', '5.8以降接種_一般接種（３回目）', '5.8以降接種_一般接種（５回目）', '5.8以降接種_一般接種（４回目）', '５回目_総接種回数', '６回目_総接種回数', '5.8以降接種_総接種回数'}"
cowidev.vax.batch.jersey,3.0,True,2023-06-02T07:00:10,,
cowidev.vax.batch.latvia,53.45,True,2023-06-02T07:01:00,,
cowidev.vax.batch.lithuania,4.51,True,2023-06-02T07:00:11,,
cowidev.vax.batch.luxembourg,1.17,False,2023-06-02T10:54:37,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 88, in main
    Luxembourg().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 83, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 78, in pipeline
    .pipe(self.pipe_correct_time_series)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/luxembourg.py"", line 47, in pipe_correct_time_series
    df = add_latest_who_values(df, ""Luxembourg"", [""people_fully_vaccinated""])
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.malaysia,0.95,True,2023-06-02T07:00:08,,
cowidev.vax.batch.malta,1.05,True,2023-06-02T07:00:08,,
cowidev.vax.batch.netherlands,,,2023-06-02T07:00:07,,
cowidev.vax.batch.new_zealand,15.75,True,2023-06-02T07:00:22,,
cowidev.vax.batch.norway,0.69,True,2023-06-02T07:00:07,,
cowidev.vax.batch.peru,4.25,True,2023-06-02T07:00:11,,
cowidev.vax.batch.portugal,,,2023-06-02T07:00:07,,
cowidev.vax.batch.romania,2.36,False,2023-06-02T07:02:08,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 159, in main
    Romania().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 144, in export
    df = df_base.copy().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/romania.py"", line 126, in pipeline
    .pipe(add_latest_who_values, ""Romania"", [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.saudi_arabia,0.94,False,2023-06-02T07:02:09,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 82, in main
    SaudiArabia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/saudi_arabia.py"", line 59, in pipeline
    return df.pipe(self.make_monotonic).pipe(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.batch.singapore,4.12,True,2023-06-02T07:00:11,,
cowidev.vax.batch.slovakia,43.33,True,2023-06-02T07:00:50,,
cowidev.vax.batch.slovenia,2.24,True,2023-06-02T07:00:09,,
cowidev.vax.batch.south_korea,56.2,False,2023-06-02T07:03:06,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 209, in main
    SouthKorea().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 191, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 43, in read
    dfs = pd.read_html(to_proxy_url(self.source_url), encoding=""utf-8"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/html.py"", line 1098, in read_html
    return _parse(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/html.py"", line 906, in _parse
    tables = p.parse_tables()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/html.py"", line 222, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/html.py"", line 745, in _build_doc
    raise e
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/html.py"", line 726, in _build_doc
    with urlopen(self.io) as f:
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/usr/lib/python3.10/urllib/request.py"", line 216, in urlopen
    return opener.open(url, data, timeout)
  File ""/usr/lib/python3.10/urllib/request.py"", line 525, in open
    response = meth(req, response)
  File ""/usr/lib/python3.10/urllib/request.py"", line 634, in http_response
    response = self.parent.error(
  File ""/usr/lib/python3.10/urllib/request.py"", line 563, in error
    return self._call_chain(*args)
  File ""/usr/lib/python3.10/urllib/request.py"", line 496, in _call_chain
    result = func(*args)
  File ""/usr/lib/python3.10/urllib/request.py"", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
",HTTP Error 500: Internal Server Error
cowidev.vax.batch.spc,27.33,True,2023-06-02T07:00:34,,
cowidev.vax.batch.sweden,17.0,True,2023-06-02T07:00:24,,
cowidev.vax.batch.switzerland,72.03,True,2023-06-02T07:01:19,,
cowidev.vax.batch.trinidad_and_tobago,3.42,True,2023-06-02T07:00:11,,
cowidev.vax.batch.ukraine,,,2023-06-02T07:00:08,,
cowidev.vax.batch.united_kingdom,17.19,True,2023-06-02T07:00:25,,
cowidev.vax.batch.united_states,17.13,True,2023-06-02T07:00:25,,
cowidev.vax.batch.uruguay,7.5,True,2023-06-02T07:00:16,,
cowidev.vax.batch.zimbabwe,4.4,True,2023-06-02T07:00:14,,
cowidev.vax.incremental.africacdc,,,2023-06-02T07:00:09,,
cowidev.vax.incremental.antigua_barbuda,,,2023-06-02T07:00:09,,
cowidev.vax.incremental.aruba,1.62,True,2023-06-02T07:00:11,,
cowidev.vax.incremental.austria,,,2023-06-02T07:00:10,,
cowidev.vax.incremental.azerbaijan,,,2023-06-02T07:00:10,,
cowidev.vax.incremental.bahrain,,,2023-06-02T07:00:10,,
cowidev.vax.incremental.bangladesh,49.69,True,2023-06-02T07:00:59,,
cowidev.vax.incremental.barbados,,,2023-06-02T07:00:10,,
cowidev.vax.incremental.brazil,0.83,True,2023-06-02T07:00:11,,
cowidev.vax.incremental.bulgaria,0.92,False,2023-06-02T07:03:06,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 68, in main
    Bulgaria().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 63, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bulgaria.py"", line 59, in pipeline
    .pipe(add_latest_who_values, self.location, [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
cowidev.vax.incremental.china,19.0,True,2023-06-02T07:00:30,,
cowidev.vax.incremental.costa_rica,,,2023-06-02T07:00:11,,
cowidev.vax.incremental.croatia,0.94,True,2023-06-02T07:00:12,,
cowidev.vax.incremental.cuba,13.18,True,2023-06-02T07:00:24,,
cowidev.vax.incremental.curacao,,,2023-06-02T07:00:11,,
cowidev.vax.incremental.cyprus,3.86,True,2023-06-02T07:00:15,,
cowidev.vax.incremental.dominican_republic,12.83,True,2023-06-02T10:55:49,,
cowidev.vax.incremental.el_salvador,11.44,True,2023-06-02T07:00:23,,
cowidev.vax.incremental.faeroe_islands,1.35,True,2023-06-02T07:00:15,,
cowidev.vax.incremental.fiji,0.0,True,2023-06-02T07:00:15,,
cowidev.vax.incremental.finland,0.73,True,2023-06-02T07:00:16,,
cowidev.vax.incremental.gabon,,,2023-06-02T07:00:15,,
cowidev.vax.incremental.georgia,6.84,True,2023-06-02T07:00:22,,
cowidev.vax.incremental.greenland,,,2023-06-02T07:00:15,,
cowidev.vax.incremental.guatemala,,,2023-06-02T07:00:15,,
cowidev.vax.incremental.guernsey,,,2023-06-02T07:00:15,,
cowidev.vax.incremental.hungary,65.02,True,2023-06-02T07:01:20,,
cowidev.vax.incremental.iceland,1.89,True,2023-06-02T07:00:17,,
cowidev.vax.incremental.india,1.48,True,2023-06-02T07:00:17,,
cowidev.vax.incremental.iran,,,2023-06-02T07:00:16,,
cowidev.vax.incremental.isle_of_man,2.69,True,2023-06-02T07:00:19,,
cowidev.vax.incremental.jamaica,8.89,True,2023-06-02T07:00:25,,
cowidev.vax.incremental.kazakhstan,7.79,True,2023-06-02T07:00:25,,
cowidev.vax.incremental.kosovo,,,2023-06-02T07:00:17,,
cowidev.vax.incremental.kyrgyzstan,5.32,True,2023-06-02T07:00:23,,
cowidev.vax.incremental.laos,1.7,True,2023-06-02T07:03:21,,
cowidev.vax.incremental.macao,6.81,False,2023-06-02T07:03:27,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 90, in main
    Macao().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 75, in export
    data = self.read()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 23, in read
    iframe_url = self._get_iframe_url(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 31, in _get_iframe_url
    elem = driver.find_element_by_id(""ICovid19Monitor"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=113.0.5672.126)

","Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=113.0.5672.126)
"
cowidev.vax.incremental.moldova,,,2023-06-02T07:00:18,,
cowidev.vax.incremental.monaco,86.97,True,2023-06-02T07:01:45,,
cowidev.vax.incremental.mongolia,1.35,True,2023-06-02T07:00:20,,
cowidev.vax.incremental.montenegro,0.93,True,2023-06-02T07:00:20,,
cowidev.vax.incremental.morocco,,,2023-06-02T07:00:20,,
cowidev.vax.incremental.myanmar,,,2023-06-02T07:00:20,,
cowidev.vax.incremental.nepal,,,2023-06-02T07:00:20,,
cowidev.vax.incremental.north_macedonia,,,2023-06-02T07:00:20,,
cowidev.vax.incremental.northern_cyprus,5.35,True,2023-06-02T07:00:25,,
cowidev.vax.incremental.paho,76.2,True,2023-06-02T10:56:52,,
cowidev.vax.incremental.pakistan,,,2023-06-02T07:00:22,,
cowidev.vax.incremental.philippines,,,2023-06-02T07:00:22,,
cowidev.vax.incremental.poland,1.87,True,2023-06-02T07:00:24,,
cowidev.vax.incremental.qatar,,,2023-06-02T07:00:22,,
cowidev.vax.incremental.russia,13.95,True,2023-06-02T07:00:36,,
cowidev.vax.incremental.saint_lucia,,,2023-06-02T07:00:22,,
cowidev.vax.incremental.serbia,10.46,True,2023-06-02T07:00:33,,
cowidev.vax.incremental.south_africa,,,2023-06-02T07:00:22,,
cowidev.vax.incremental.spain,8.98,True,2023-06-02T07:00:31,,
cowidev.vax.incremental.sri_lanka,,,2023-06-02T07:00:23,,
cowidev.vax.incremental.suriname,14.75,True,2023-06-02T07:00:37,,
cowidev.vax.incremental.taiwan,6.01,False,2023-06-02T07:04:57,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 184, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 170, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 38, in read
    data = self.parse_data(df, soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 122, in parse_data
    ""date"": self._parse_date(soup),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 156, in _parse_date
    date_str = re.search(regex, date_raw).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
",'NoneType' object has no attribute 'group'
cowidev.vax.incremental.thailand,5.97,True,2023-06-02T07:00:30,,
cowidev.vax.incremental.turkey,,,2023-06-02T07:00:24,,
cowidev.vax.incremental.united_arab_emirates,,,2023-06-02T07:00:24,,
cowidev.vax.incremental.vietnam,,,2023-06-02T07:00:24,,
cowidev.vax.incremental.who,2.53,True,2023-06-02T11:36:25,,
cowidev.vax.incremental.zambia,1.05,False,2023-06-02T07:04:58,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 74, in main
    Zambia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 69, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/zambia.py"", line 64, in pipeline
    .pipe(add_latest_who_values, ""Zambia"", [""people_vaccinated""])
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 89, in add_latest_who_values
    who = pd.read_csv(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py"", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py"", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py"", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']
","Usecols do not match columns, columns expected but not found: ['PERSONS_FULLY_VACCINATED']"
